server:
  port: 8008
spring:
  application:
    name: @artifactId@
  redis:
    host: 172.18.164.39
  main:
    allow-bean-definition-overriding: true
tio:
  core:
    server:
      port: 5678
      heartbeat-timeout: 60000
    cluster:
      enabled: false
